# -*- coding: utf-8 -*-
# Интерфейс симулятора раскроя
__author__ = "Dmitry Goncharov"
__version__ = "1.0"
__date__ = "2018-06-17"
__status__ = "beta"
__email__ = "igonchik@gmail.com"


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        curp = os.path.join(os.path.dirname(__file__), 'icons')

        #Шрифт
        fontb = QtGui.QFont()
        fontb.setPointSize(12)
        fontb.setWeight(75)
        fontb2 = QtGui.QFont()
        fontb2.setPointSize(22)
        fontb2.setWeight(75)
        fontr = QtGui.QFont()
        fontr.setPointSize(22)
        fontr.setWeight(75)
        font = QtGui.QFont()
        font.setPointSize(12)
        fontabout = QtGui.QFont()
        fontabout.setPointSize(13)

        #Главное окно
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setAutoFillBackground(False)
        self.fone = QtWidgets.QLabel(self.centralwidget)
        self.fone1 = QtWidgets.QLabel(self.centralwidget)
        self.text_upor_l1 = QtWidgets.QLabel()
        self.text_upor_l2 = QtWidgets.QLabel()
        self.text_upor_r = QtWidgets.QLabel()
        self.text_detal = QtWidgets.QLabel()
        self.text_detal_alarm = QtWidgets.QLabel()
        self.btn_mapl = QtWidgets.QPushButton()
        self.btn_mapr = QtWidgets.QPushButton()
        self.text_map = QtWidgets.QLabel()
        self.text_plita = QtWidgets.QLabel()
        self.text_zakaz = QtWidgets.QLabel()
        self.text_material = QtWidgets.QLabel()
        self.text_map.setFont(fontb)
        self.text_plita.setFont(fontb)
        self.text_material.setFont(fontb)
        self.text_zakaz.setFont(fontb)
        self.picture = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.picture.sizePolicy().hasHeightForWidth())
        self.picture.setSizePolicy(sizePolicy)
        self.picture.setMinimumSize(QtCore.QSize(300, 130))
        self.picture2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.picture2.sizePolicy().hasHeightForWidth())
        self.picture2 = QtWidgets.QLabel(self.centralwidget)
        self.picture2.setSizePolicy(sizePolicy)
        self.picture2.setMinimumSize(QtCore.QSize(300, 110))
        self.text_upor_rt = QtWidgets.QLabel(self.centralwidget)
        self.text_upor_l1t = QtWidgets.QLabel(self.centralwidget)
        self.text_upor_l2t = QtWidgets.QLabel(self.centralwidget)
        self.text_upor_l2t.setAlignment(QtCore.Qt.AlignRight)
        self.text_upor_l1t.setAlignment(QtCore.Qt.AlignRight)
        self.text_upor_rt.setAlignment(QtCore.Qt.AlignRight)
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture2.setAlignment(QtCore.Qt.AlignCenter)
        self.text_upor_l1 = QtWidgets.QLabel(self.centralwidget)
        self.text_upor_l2 = QtWidgets.QLabel(self.centralwidget)
        self.text_upor_r = QtWidgets.QLabel(self.centralwidget)
        self.text_upor_l1.setFont(fontb2)
        self.text_upor_l2.setFont(fontb2)
        self.text_upor_r.setFont(fontb2)
        self.text_upor_l2.setAlignment(QtCore.Qt.AlignRight)
        self.text_upor_l1.setAlignment(QtCore.Qt.AlignRight)
        self.text_upor_r.setAlignment(QtCore.Qt.AlignRight)
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setFixedSize(120, 120)
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setFixedSize(120, 120)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setFixedSize(120, 120)
        self.btn_mapl.setIconSize(QtCore.QSize(32,32))
        self.btn_mapr.setIconSize(QtCore.QSize(32,32))
        self.prevButton.setIconSize(QtCore.QSize(32,32))
        self.nextButton.setIconSize(QtCore.QSize(32,32))
        self.openButton.setIconSize(QtCore.QSize(32,32))
        self.openButton.setIcon(QtGui.QIcon(os.path.join(curp, "document-open.png")))
        self.prevButton.setIcon(QtGui.QIcon(os.path.join(curp, "arrow-left.png")))
        self.nextButton.setIcon(QtGui.QIcon(os.path.join(curp, "arrow-right.png")))
        self.btn_mapr.setIcon(QtGui.QIcon(os.path.join(curp, "go-last-view.png")))
        self.btn_mapl.setIcon(QtGui.QIcon(os.path.join(curp, "go-first-view.png")))
        self.text_upor_l1t.setFont(fontabout)
        self.text_upor_l2t.setFont(fontabout)
        self.text_upor_rt.setFont(fontabout)
        self.text_upor_l2t.setPixmap(QtGui.QPixmap(os.path.join(curp, "align-horizontal-right.png")))
        self.text_detal_alarm.setFont(fontr)
        self.text_detal_alarm.setStyleSheet('color: red')
        self.text_detal.setAlignment(QtCore.Qt.AlignCenter)
        self.text_detal.setFont(font)
        self.pic1_bg = QtWidgets.QLabel(self.centralwidget)
        self.pic1_bg = QtWidgets.QLabel(self.centralwidget)

        # Расположение элементов в окне
        self.grid = QtWidgets.QGridLayout()
        self.grid.setSpacing(5)
        self.grid.addWidget(self.btn_mapl, 0, 0, 2, 2)
        self.grid.addWidget(self.btn_mapr,0,3,2,2)
        self.grid.addWidget(self.text_map, 0, 5, 1, 10)
        self.grid.addWidget(self.text_plita,1, 5, 1, 10)
        self.grid.addWidget(self.text_zakaz,0, 16, 1, 10)
        self.grid.addWidget(self.text_material, 1, 16, 1, 10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.grid)
        self.verticalLayout_2.addWidget(self.picture)
        self.verticalLayout_2.addWidget(self.picture2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.addWidget(self.text_upor_l2t, 0 , QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.text_upor_l1t, 0 , QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.text_upor_rt, 0 , QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.addWidget(self.text_upor_l2, 0 , QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.text_upor_l1, 0 , QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.text_upor_r, 0 , QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.addWidget(self.text_detal)
        self.horizontalLayout3.addWidget(self.text_detal_alarm)
        self.verticalLayout_2.addLayout(self.horizontalLayout3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.addWidget(self.openButton, 0 , QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setStretch(0, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Симулятор раскроя"))
        self.picture.setText(_translate("MainWindow", ""))
        self.picture2.setText(_translate("MainWindow", ""))
        self.openButton.setText(_translate("MainWindow", ""))
        self.prevButton.setText(_translate("MainWindow", ""))
        self.nextButton.setText(_translate("MainWindow", ""))
        self.text_plita.setText(_translate("MainWindow", ""))
        self.text_map.setText(_translate("MainWindow", "  Карта: 0/0"))
        self.text_material.setText(_translate("MainWindow", " Материал:"))
        self.text_zakaz.setText(_translate("MainWindow", " Заказ:"))
        self.text_upor_l1.setText("0")
        self.text_upor_l2.setText("")
        self.text_upor_r.setText("0")
        self.text_upor_l1t.setText("Левый упор 1")
        self.text_upor_l2t.setText("Текстура")
        self.text_upor_rt.setText("Правый упор")
        self.statusbar.show()
        self.statusbar.showMessage("Для начала работы выберите файл раскроя")
        self.nextButton.setDisabled(True)
        self.prevButton.setDisabled(True)
        self.btn_mapl.setDisabled(True)
        self.btn_mapr.setDisabled(True)
